# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234fa1a01b469e82517c3d981a7b0a2bb168cc467ae69b904257528d6f59157b5bd4ab65aa52b4328f736eadb4c7df6ca9c6ce3d9daaf3b417431510dbd01fda

test:
  secret_key_base: 5578960a8d2e8b7bb2e34716f771ff38296ac3730661229e0f1ca59fdf8a3dc70395e54686b9c017d70a7e18fff6df083d84aa3279a76a063c094e0984f0cf52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
