# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98b6bd57b3118cfc0def903c706de56696c8245676d09082ee73dea94fc0b007befe3928bb2a201a75de91169fe2707022fbca13ebd3337713664f7c2d193e5

test:
  secret_key_base: 6d71f23c7907d45663fcd0531a5c51f47413dc30e7fa193326b2030f8d91ebb8c3e8257e714e7339fa8ef7148577ce9cd87fa8f3200abc82fa230f5da694856e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
